# Generated by Django 4.2.5 on 2023-09-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Номер чата'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Номер последнего сообщения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
