# Generated by Django 4.2.5 on 2023-09-28 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='Место')),
                ('time', models.DateTimeField(verbose_name='Время когда необходимо выполнить привычку')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('nice_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('period', models.SmallIntegerField(verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознаграждение')),
                ('length', models.SmallIntegerField(verbose_name='Продолжительность')),
                ('public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('linked_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная приывычка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
