# Generated by Django 4.2.5 on 2023-09-25 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='Место')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('nice_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('period', models.CharField(choices=[('EVERY DAY', 'раз в день'), ('EVERY OTHER DAY', 'через день'), ('EVERY WEEK', 'раз в неделю')], default='EVERY_DAY', max_length=100, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознаграждение')),
                ('length', models.SmallIntegerField(verbose_name='Продолжительность')),
                ('public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('linked_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная приывычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
