# Generated by Django 4.2.5 on 2023-09-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.SmallIntegerField(verbose_name='Периодичность'),
        ),
    ]
